version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-mongo-username   # MongoDB kullanıcı adı
      MONGO_INITDB_ROOT_PASSWORD: your-mongo-password   # MongoDB şifre

volumes:
  mongodb_data:
