spring:
  data:
    mongodb:
      host: localhost        # MongoDB sunucu adresi
      port: 27017            # MongoDB bağlantı noktası
      database: mydb         # MongoDB veritabanı adı
      username: your-mongo-username   # MongoDB kullanıcı adı
      password: your-mongo-password    # MongoDB şifre
      authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080


